/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPack;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static mainPack.DB.admin;
import props.Customer;

/**
 *
 * @author touch
 */
public final class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    private Customer selectedCustomer = new Customer();
    private int selectedOrderId = -1;
    private String selectedOrderStatus = "";

    TableRowSorter<TableModel> sorterCustomerTable;
    TableRowSorter<TableModel> sorterOrderTable;

    public DashboardFrame() {
        initComponents();
        refreshCustomerTable();
        refreshOrderTable();
        buttonCustomerDelete.setEnabled(false);
        buttonCustomerUpdate.setEnabled(false);
        buttonOrderAddDialog.setEnabled(false);
        buttonOrderDelete.setEnabled(false);
        buttonOrderStatusUpdate.setEnabled(false);
        
         if(tableOrders.getRowCount() == 0 ){
            buttonDeleteAllOrders.setEnabled(false);
        }
         
         labelAdminID.setText("Admin ID : " + String.valueOf(admin.getId()));
         labelAdminName.setText(admin.getName());
         labelAdminEmail.setText(admin.getEmail());

    }

    public void refreshCustomerTable() {
        DB db = new DB();
        tableCustomers.setModel(db.listCustomers());
        sorterCustomerTable = new TableRowSorter<>(db.listCustomers());
        db.close();
    }

    public void refreshOrderTable() {
        DB db = new DB();
        tableOrders.setModel(db.listOrders());
        sorterOrderTable = new TableRowSorter<>(db.listOrders());
        db.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearchName = new javax.swing.JTextField();
        txtSearchSurName = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttonCustomerAddDialog = new javax.swing.JButton();
        buttonCustomerDelete = new javax.swing.JButton();
        buttonCustomerUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrders = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buttonOrderAddDialog = new javax.swing.JButton();
        buttonOrderDelete = new javax.swing.JButton();
        buttonOrderStatusUpdate = new javax.swing.JButton();
        buttonDeleteAllOrders = new javax.swing.JButton();
        buttonListTodaysOrders = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        buttonMinimize = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelAdminID = new javax.swing.JLabel();
        labelAdminName = new javax.swing.JLabel();
        labelAdminEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(DashboardFrame.MAXIMIZED_BOTH);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true), "Müşteri Ara", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        txtSearchName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true), "Adı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txtSearchSurName.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true), "Soyadı", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonSearch.setBackground(new java.awt.Color(51, 153, 255));
        buttonSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setText("Ara");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtSearchSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/big_water.png"))); // NOI18N

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true), "Müşteriler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jScrollPane1.setToolTipText("");
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Adı", "Soyisim", "Telefon", "Adres"
            }
        ));
        tableCustomers.setGridColor(new java.awt.Color(51, 153, 255));
        tableCustomers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableCustomersFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableCustomersFocusLost(evt);
            }
        });
        tableCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableCustomersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomers);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonCustomerAddDialog.setBackground(new java.awt.Color(51, 153, 255));
        buttonCustomerAddDialog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonCustomerAddDialog.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomerAddDialog.setText("+");
        buttonCustomerAddDialog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCustomerAddDialog.setIconTextGap(0);
        buttonCustomerAddDialog.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonCustomerAddDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerAddDialogActionPerformed(evt);
            }
        });

        buttonCustomerDelete.setBackground(new java.awt.Color(51, 153, 255));
        buttonCustomerDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonCustomerDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomerDelete.setText("-");
        buttonCustomerDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCustomerDelete.setIconTextGap(0);
        buttonCustomerDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerDeleteActionPerformed(evt);
            }
        });

        buttonCustomerUpdate.setBackground(new java.awt.Color(51, 153, 255));
        buttonCustomerUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonCustomerUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustomerUpdate.setText("Güncelle");
        buttonCustomerUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCustomerUpdate.setIconTextGap(0);
        buttonCustomerUpdate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonCustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 371, Short.MAX_VALUE)
                .addComponent(buttonCustomerUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustomerDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCustomerAddDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(buttonCustomerAddDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonCustomerDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(buttonCustomerUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 2, true), "Siparişler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Müşteri Adı", "Müşteri Soyadı", "Durum", "Adres", "Tutar (TL)"
            }
        ));
        tableOrders.setGridColor(new java.awt.Color(51, 153, 255));
        tableOrders.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableOrdersFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableOrdersFocusLost(evt);
            }
        });
        tableOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableOrdersMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableOrders);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        buttonOrderAddDialog.setBackground(new java.awt.Color(51, 153, 255));
        buttonOrderAddDialog.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonOrderAddDialog.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrderAddDialog.setText("+");
        buttonOrderAddDialog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOrderAddDialog.setIconTextGap(0);
        buttonOrderAddDialog.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonOrderAddDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderAddDialogActionPerformed(evt);
            }
        });

        buttonOrderDelete.setBackground(new java.awt.Color(51, 153, 255));
        buttonOrderDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonOrderDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrderDelete.setText("-");
        buttonOrderDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOrderDelete.setIconTextGap(0);
        buttonOrderDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonOrderDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderDeleteActionPerformed(evt);
            }
        });

        buttonOrderStatusUpdate.setBackground(new java.awt.Color(51, 153, 255));
        buttonOrderStatusUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonOrderStatusUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrderStatusUpdate.setText("Durum Güncelle");
        buttonOrderStatusUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOrderStatusUpdate.setIconTextGap(0);
        buttonOrderStatusUpdate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonOrderStatusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderStatusUpdateActionPerformed(evt);
            }
        });

        buttonDeleteAllOrders.setBackground(new java.awt.Color(255, 51, 51));
        buttonDeleteAllOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonDeleteAllOrders.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeleteAllOrders.setText("Tümünü Sil");
        buttonDeleteAllOrders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDeleteAllOrders.setIconTextGap(0);
        buttonDeleteAllOrders.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonDeleteAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteAllOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(buttonDeleteAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOrderStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonOrderAddDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOrderAddDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrderStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeleteAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        buttonListTodaysOrders.setBackground(new java.awt.Color(51, 153, 255));
        buttonListTodaysOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonListTodaysOrders.setForeground(new java.awt.Color(255, 255, 255));
        buttonListTodaysOrders.setText("Bugünün Siparişleri");
        buttonListTodaysOrders.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonListTodaysOrders.setIconTextGap(0);
        buttonListTodaysOrders.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonListTodaysOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListTodaysOrdersActionPerformed(evt);
            }
        });

        buttonClose.setBackground(new java.awt.Color(255, 255, 255));
        buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/icon_close.png"))); // NOI18N
        buttonClose.setBorder(null);
        buttonClose.setBorderPainted(false);
        buttonClose.setContentAreaFilled(false);
        buttonClose.setFocusPainted(false);
        buttonClose.setFocusable(false);
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        buttonMinimize.setBackground(new java.awt.Color(255, 255, 255));
        buttonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/icon_minimize.png"))); // NOI18N
        buttonMinimize.setBorder(null);
        buttonMinimize.setBorderPainted(false);
        buttonMinimize.setContentAreaFilled(false);
        buttonMinimize.setMaximumSize(new java.awt.Dimension(16, 16));
        buttonMinimize.setMinimumSize(new java.awt.Dimension(16, 16));
        buttonMinimize.setPreferredSize(new java.awt.Dimension(16, 16));
        buttonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinimizeActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPack/bottom_background_water.jpg"))); // NOI18N

        labelAdminID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAdminID.setText("jLabel3");

        labelAdminName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAdminName.setText("jLabel3");

        labelAdminEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAdminEmail.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonListTodaysOrders)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(314, 314, 314)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(buttonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonClose)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1450, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonMinimize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonClose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(labelAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(labelAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(buttonListTodaysOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomerAddDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerAddDialogActionPerformed

        CustomerFormFrame addCustomerFrame = new CustomerFormFrame(this);
        addCustomerFrame.setVisible(true);
        this.setEnabled(false);
        buttonCustomerDelete.setEnabled(false);
        buttonCustomerUpdate.setEnabled(false);
        buttonOrderAddDialog.setEnabled(false);


    }//GEN-LAST:event_buttonCustomerAddDialogActionPerformed

    private void buttonCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerDeleteActionPerformed

        int id = selectedCustomer.getId();

        String[] options = new String[2];
        options[0] = "Evet";
        options[1] = "Hayır";
        int dialogResult = JOptionPane.showOptionDialog(rootPane, "Seçili müşteriyi silmek istediğinize emin misiniz? ", "Müşteri Sil", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);

        if (dialogResult == JOptionPane.YES_OPTION) {

            DB db = new DB();
            int status = db.deleteCustomer(id);
            db.close();
            if (status > 0) {
                refreshCustomerTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarısız!");

            }
        }

        buttonCustomerDelete.setEnabled(false);
        buttonCustomerUpdate.setEnabled(false);
        buttonOrderAddDialog.setEnabled(false);


    }//GEN-LAST:event_buttonCustomerDeleteActionPerformed

    private void tableCustomersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomersMouseReleased

        int row = tableCustomers.getSelectedRow();
        int id = (int) tableCustomers.getValueAt(row, 0);
        String name = (String) tableCustomers.getValueAt(row, 1);
        String surName = (String) tableCustomers.getValueAt(row, 2);
        String phoneNumber = (String) tableCustomers.getValueAt(row, 3);
        String address = (String) tableCustomers.getValueAt(row, 4);

        selectedCustomer.setId(id);
        selectedCustomer.setName(name);
        selectedCustomer.setSurName(surName);
        selectedCustomer.setPhoneNumber(phoneNumber);
        selectedCustomer.setAddress(address);

    }//GEN-LAST:event_tableCustomersMouseReleased

    private void buttonCustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerUpdateActionPerformed

        CustomerFormFrame addCustomerFrame = new CustomerFormFrame(this, this.selectedCustomer);
        addCustomerFrame.setVisible(true);
        this.setEnabled(false);

        buttonCustomerDelete.setEnabled(false);
        buttonCustomerUpdate.setEnabled(false);
        buttonOrderAddDialog.setEnabled(false);

    }//GEN-LAST:event_buttonCustomerUpdateActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed

        String name = txtSearchName.getText().trim();
        String surName = txtSearchSurName.getText().trim();

        tableCustomers.setRowSorter(sorterCustomerTable);

        if (name.length() != 0 && surName.length() != 0) {
            sorterCustomerTable.setRowFilter(RowFilter.regexFilter(name, 1));
            sorterCustomerTable.setRowFilter(RowFilter.regexFilter(surName, 2));
        } else if (name.length() != 0 && surName.length() == 0) {
            sorterCustomerTable.setRowFilter(RowFilter.regexFilter(name, 1));
        } else if (name.length() == 0 && surName.length() != 0) {
            sorterCustomerTable.setRowFilter(RowFilter.regexFilter(surName, 2));
        } else {
            sorterCustomerTable.setRowFilter(null);
        }

    }//GEN-LAST:event_buttonSearchActionPerformed

    private void tableOrdersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrdersMouseReleased

        int row = tableOrders.getSelectedRow();
        selectedOrderId = (int) tableOrders.getValueAt(row, 0);
        selectedOrderStatus = (String) tableOrders.getValueAt(row, 3);

    }//GEN-LAST:event_tableOrdersMouseReleased

    private void buttonOrderAddDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderAddDialogActionPerformed

        OrderFormFrame orderFormFrame = new OrderFormFrame(this, this.selectedCustomer);
        orderFormFrame.setVisible(true);
        this.setEnabled(false);

        buttonDeleteAllOrders.setEnabled(true);

    }//GEN-LAST:event_buttonOrderAddDialogActionPerformed

    private void buttonOrderDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderDeleteActionPerformed

        String[] options = new String[2];
        options[0] = "Sil";
        options[1] = "İptal";
        int dialogResult = JOptionPane.showOptionDialog(rootPane, "Seçili siparişi silmek istediğinize emin misiniz? ", "Sipariş Sil", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);

        if (dialogResult == JOptionPane.YES_OPTION) {

            DB db = new DB();
            int status = db.deleteOrder(selectedOrderId);
            db.close();
            if (status > 0) {
                refreshOrderTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarısız!");

            }
        }
        buttonOrderDelete.setEnabled(false);
        buttonOrderStatusUpdate.setEnabled(false);
        
         if(tableOrders.getRowCount() == 0 ){
            buttonDeleteAllOrders.setEnabled(false);
        }
    }//GEN-LAST:event_buttonOrderDeleteActionPerformed

    private void buttonOrderStatusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderStatusUpdateActionPerformed
        OrderStatusFrame orderStatusFrame = new OrderStatusFrame(this, selectedOrderId, selectedOrderStatus);
        orderStatusFrame.setVisible(true);
        this.setEnabled(false);

        buttonOrderAddDialog.setEnabled(false);
        buttonOrderDelete.setEnabled(false);
        buttonOrderStatusUpdate.setEnabled(false);
    }//GEN-LAST:event_buttonOrderStatusUpdateActionPerformed

    private void tableOrdersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableOrdersFocusGained

        buttonOrderDelete.setEnabled(true);
        buttonOrderStatusUpdate.setEnabled(true);
    }//GEN-LAST:event_tableOrdersFocusGained

    private void tableOrdersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableOrdersFocusLost

    }//GEN-LAST:event_tableOrdersFocusLost

    private void tableCustomersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableCustomersFocusGained

        buttonCustomerDelete.setEnabled(true);
        buttonCustomerUpdate.setEnabled(true);
        buttonOrderAddDialog.setEnabled(true);


    }//GEN-LAST:event_tableCustomersFocusGained

    private void tableCustomersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableCustomersFocusLost
    }//GEN-LAST:event_tableCustomersFocusLost

    private void buttonListTodaysOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListTodaysOrdersActionPerformed

        String buttonText = buttonListTodaysOrders.getText().trim();
        if (buttonText.equals("Tüm Siparişler")) {
            sorterOrderTable.setRowFilter(null);
            buttonListTodaysOrders.setText("Bugünün Siparişleri");
        } else {
            tableOrders.setRowSorter(sorterOrderTable);
            sorterOrderTable.setRowFilter(RowFilter.regexFilter("Hazırlanıyor", 3));
            buttonListTodaysOrders.setText("Tüm Siparişler");
        }


    }//GEN-LAST:event_buttonListTodaysOrdersActionPerformed

    private void buttonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinimizeActionPerformed

        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonDeleteAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteAllOrdersActionPerformed

        String[] options = new String[2];
        options[0] = "Sil";
        options[1] = "İptal";
        int dialogResult = JOptionPane.showOptionDialog(rootPane, "Tüm siparişleri silmek istediğinize emin misiniz? ", "Tümünü Sil", 0, JOptionPane.INFORMATION_MESSAGE, null, options, null);

        if (dialogResult == JOptionPane.YES_OPTION) {

            DB db = new DB();
            int status = db.deleteAllOrders();
            db.close();
            if (status > 0) {                
                refreshOrderTable();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Silme işlemi başarısız!");

            }
        }

        if(tableOrders.getRowCount() == 0 ){
            buttonDeleteAllOrders.setEnabled(false);
        }
    }//GEN-LAST:event_buttonDeleteAllOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonCustomerAddDialog;
    private javax.swing.JButton buttonCustomerDelete;
    private javax.swing.JButton buttonCustomerUpdate;
    private javax.swing.JButton buttonDeleteAllOrders;
    private javax.swing.JButton buttonListTodaysOrders;
    private javax.swing.JButton buttonMinimize;
    private javax.swing.JButton buttonOrderAddDialog;
    private javax.swing.JButton buttonOrderDelete;
    private javax.swing.JButton buttonOrderStatusUpdate;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAdminEmail;
    private javax.swing.JLabel labelAdminID;
    private javax.swing.JLabel labelAdminName;
    private javax.swing.JTable tableCustomers;
    private javax.swing.JTable tableOrders;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txtSearchSurName;
    // End of variables declaration//GEN-END:variables
}
